version: '3'
name: 'bvarta-geodata-management-system'

networks:
  bvarta_geodata_management_system:
    driver: bridge
    
volumes:
  mongodb_data:

services:
  app:
    build: ../app
    networks:
      - bvarta_geodata_management_system
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    networks:
      - bvarta_geodata_management_system
    ports:
      - "27017:27017"